### ISSUE TITLE
plugin hangs on non existing ip

### ISSUE THREAD

**Issue by zoiba** [BastiaanOlij/gdvnc#1]
the plugin hangs for a while if there is't a pc at the given ip

**Comment by BastiaanOlij** [comment]
It's probably just waiting to time out.. I need to see if I can change the timeout duration. Otherwise we need to look into running the VNC communication in a separate thread

**Comment by BastiaanOlij** [comment]
I couldn't set the timeout but now that we've got the connection running in another thread it should no longer hang the PC. The timeout I think is around a minute so if the vnc server can't be reached the connection attempt will fail after that timeout.
