### ISSUE TITLE
plugin crash if there were no vnc server running

### ISSUE THREAD

**Issue by zoiba** [BastiaanOlij/gdvnc#2]
the plugin crashes if there isn't a vnc server running on the given ip

**Comment by BastiaanOlij** [comment]
Auch.. I'll see if I can find out why, it sounds like it doesn't clean up nicely and just assumes the server is there..

**Comment by BastiaanOlij** [comment]
When connection fails libvnc already cleans up the memory allocated to track the client session. When we subsequently tried to clean up it crashed. Should be fixed now.
